# Generated by Django 4.2.2 on 2023-06-26 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('dob', models.IntegerField(max_length=8)),
                ('parent_name', models.CharField(max_length=25)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=25)),
                ('phone', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.IntegerField(default=None, max_length=2)),
                ('maths', models.IntegerField(default=None, max_length=2)),
                ('science', models.IntegerField(default=None, max_length=2)),
                ('hindi', models.IntegerField(default=None, max_length=2)),
                ('social_science', models.IntegerField(default=None, max_length=2)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.student')),
            ],
        ),
    ]
