# Generated by Django 4.2.2 on 2023-06-26 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marks',
            old_name='student_id',
            new_name='student',
        ),
    ]
