# Generated by Django 4.2.2 on 2023-06-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_rename_student_id_marks_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='english',
            field=models.IntegerField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='hindi',
            field=models.IntegerField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='maths',
            field=models.IntegerField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='science',
            field=models.IntegerField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='social_science',
            field=models.IntegerField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.IntegerField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
