# Generated by Django 4.2.2 on 2023-06-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_alter_marks_english_alter_marks_hindi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='percentage',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='marks',
            name='english',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='marks',
            name='hindi',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='marks',
            name='maths',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='marks',
            name='science',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='marks',
            name='social_science',
            field=models.IntegerField(default=None),
        ),
    ]
